"""empty message

Revision ID: 2006392b2924
Revises: ec6c582ad4c5
Create Date: 2024-01-09 19:49:23.623177

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2006392b2924'
down_revision = 'ec6c582ad4c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pendings_providers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=225), nullable=True),
    sa.Column('request_date', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('ticket_associated', sa.String(length=50), nullable=True),
    sa.Column('finished', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('pendings_units')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pendings_units',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('description', sa.VARCHAR(length=225), autoincrement=False, nullable=True),
    sa.Column('request_date', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('ticket_associated', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('finished', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('provider', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='pendings_units_pkey')
    )
    op.drop_table('pendings_providers')
    # ### end Alembic commands ###
