"""empty message

Revision ID: 272615edb62b
Revises: ef4e0061e5bd
Create Date: 2024-01-08 18:46:41.533838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '272615edb62b'
down_revision = 'ef4e0061e5bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pendings_units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=225), nullable=True),
    sa.Column('request_date', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('ticket_associated', sa.String(length=50), nullable=True),
    sa.Column('finished', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pendings_units')
    # ### end Alembic commands ###
