"""empty message

Revision ID: 288d39070210
Revises: 68cef7a0575d
Create Date: 2023-11-25 20:13:08.233683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '288d39070210'
down_revision = '68cef7a0575d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.alter_column('control_incidente',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('control_cambio_cor',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('control_cambio_dcce',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('actividad',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('actividad_satisfactoria',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.alter_column('actividad_satisfactoria',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('actividad',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('control_cambio_dcce',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('control_cambio_cor',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('control_incidente',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###
