"""empty message

Revision ID: 2e8fb7882916
Revises: 288d39070210
Create Date: 2023-11-25 22:06:55.710810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e8fb7882916'
down_revision = '288d39070210'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.alter_column('fecha_actividad',
               existing_type=sa.DATE(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.alter_column('fecha_actividad',
               existing_type=sa.DATE(),
               nullable=False)

    # ### end Alembic commands ###
