"""empty message

Revision ID: 3e86e1d56b18
Revises: f57348a19698
Create Date: 2023-12-12 19:41:05.474244

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3e86e1d56b18'
down_revision = 'f57348a19698'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('temperature', schema=None) as batch_op:
        batch_op.alter_column('measurement_time',
               existing_type=postgresql.TIME(),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.alter_column('measurement_date',
               existing_type=sa.DATE(),
               type_=sa.String(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('temperature', schema=None) as batch_op:
        batch_op.alter_column('measurement_date',
               existing_type=sa.String(length=20),
               type_=sa.DATE(),
               existing_nullable=False)
        batch_op.alter_column('measurement_time',
               existing_type=sa.String(length=20),
               type_=postgresql.TIME(),
               existing_nullable=False)

    # ### end Alembic commands ###
