"""empty message

Revision ID: 618883dd9414
Revises: ebe5adc073d2
Create Date: 2023-12-09 21:50:58.140335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '618883dd9414'
down_revision = 'ebe5adc073d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('temperature_reading',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('air_unit', sa.String(length=20), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('reading_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('maintenance_evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('evidence_file', sa.LargeBinary(), nullable=False),
    sa.Column('create_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('maintenance_evidence')
    op.drop_table('temperature_reading')
    # ### end Alembic commands ###
