"""empty message

Revision ID: 68cef7a0575d
Revises: 5d6cf191c33e
Create Date: 2023-11-25 20:01:31.730727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68cef7a0575d'
down_revision = '5d6cf191c33e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_actividad', sa.Date(), nullable=False),
    sa.Column('control_incidente', sa.String(length=50), nullable=False),
    sa.Column('control_cambio_cor', sa.String(length=50), nullable=False),
    sa.Column('control_cambio_dcce', sa.String(length=50), nullable=False),
    sa.Column('tecnico_nombre_apellido', sa.String(length=50), nullable=False),
    sa.Column('personal_infra_nombre_apellido', sa.String(length=50), nullable=False),
    sa.Column('actividad', sa.String(length=50), nullable=False),
    sa.Column('actividad_satisfactoria', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activity')
    # ### end Alembic commands ###
