"""empty message

Revision ID: 8bb66391ba29
Revises: 
Create Date: 2023-11-27 18:59:15.993352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bb66391ba29'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_actividad', sa.Date(), nullable=False),
    sa.Column('control_incidente', sa.String(length=50), nullable=True),
    sa.Column('control_cambio_cor', sa.String(length=50), nullable=True),
    sa.Column('control_cambio_dcce', sa.String(length=50), nullable=True),
    sa.Column('tecnico_nombre_apellido', sa.String(length=50), nullable=False),
    sa.Column('personal_infra_nombre_apellido', sa.String(length=50), nullable=False),
    sa.Column('actividad', sa.String(length=50), nullable=True),
    sa.Column('actividad_satisfactoria', sa.Boolean(), nullable=True),
    sa.Column('tipo_de_mantenimiento', sa.String(length=50), nullable=True),
    sa.Column('observaciones', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('surname', sa.String(length=20), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('emailDCH', sa.String(length=120), nullable=False),
    sa.Column('jobPosition', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=120), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('salt', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('emailDCH')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('activity')
    # ### end Alembic commands ###
