"""empty message

Revision ID: 8f8bc08194b7
Revises: 618883dd9414
Create Date: 2023-12-09 21:56:19.178366

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8f8bc08194b7'
down_revision = '618883dd9414'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('temperature',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('air_unit', sa.String(length=20), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('measurement_time', sa.Time(), nullable=False),
    sa.Column('measurement_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('temperature_reading')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('temperature_reading',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('air_unit', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('temperature', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('reading_time', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='temperature_reading_pkey')
    )
    op.drop_table('temperature')
    # ### end Alembic commands ###
