"""empty message

Revision ID: cb39a7c81acd
Revises: ebc095186309
Create Date: 2023-12-03 12:32:55.793077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb39a7c81acd'
down_revision = 'ebc095186309'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_name', sa.String(length=255), nullable=False),
    sa.Column('document_type', sa.String(length=255), nullable=False),
    sa.Column('document_version', sa.String(length=255), nullable=False),
    sa.Column('document_unit', sa.String(length=255), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('documents')
    # ### end Alembic commands ###
