"""empty message

Revision ID: f57348a19698
Revises: 
Create Date: 2023-12-12 19:22:29.131958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f57348a19698'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_actividad', sa.Date(), nullable=False),
    sa.Column('control_incidente', sa.String(length=50), nullable=True),
    sa.Column('control_cambio_cor', sa.String(length=50), nullable=True),
    sa.Column('control_cambio_dcce', sa.String(length=50), nullable=True),
    sa.Column('tecnico_nombre_apellido', sa.String(length=50), nullable=False),
    sa.Column('personal_infra_nombre_apellido', sa.String(length=50), nullable=False),
    sa.Column('actividad', sa.String(length=50), nullable=True),
    sa.Column('actividad_satisfactoria', sa.Boolean(), nullable=True),
    sa.Column('tipo_de_mantenimiento', sa.String(length=50), nullable=True),
    sa.Column('observaciones', sa.String(length=50), nullable=True),
    sa.Column('create_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_name', sa.String(length=255), nullable=False),
    sa.Column('document_type', sa.String(length=255), nullable=False),
    sa.Column('document_version', sa.String(length=255), nullable=False),
    sa.Column('document_unit', sa.String(length=255), nullable=False),
    sa.Column('document_file', sa.String(length=255), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('temperature',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('air_unit', sa.String(length=20), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('measurement_time', sa.Time(), nullable=False),
    sa.Column('measurement_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('surname', sa.String(length=20), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('emailDCH', sa.String(length=120), nullable=False),
    sa.Column('jobPosition', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=120), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('salt', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('emailDCH')
    )
    op.create_table('maintenance_evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('evidence_file', sa.LargeBinary(), nullable=False),
    sa.Column('create_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('maintenance_evidence')
    op.drop_table('user')
    op.drop_table('temperature')
    op.drop_table('documents')
    op.drop_table('activity')
    # ### end Alembic commands ###
